name: Release pdf 

on:
  push:
    branches: [ master ]

jobs:
       
  archive-build-artifacts:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Create a temporary folder
        run: |
          sudo apt install pandoc pdftk texlive-latex-base texlive-xetex
          mkdir ttt re output
          git clone https://github.com/XHNan/PentestNotes.git
          curl https://raw.githubusercontent.com/XHNan/PentestNotes/page/createpdf.py -L -o tt.py
          python3 tt.py
          pdftk ./re/*.pdf ./ttt/*.pdf cat output ./output/pentestnotes.pdf      
      - name: Delete Release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          tag_name: lastest #(required) tag name to delete 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ steps.set_release_name.outputs.release_name }}
          body: |
            Release created on $(date +'%Y-%m-%d')
          draft: false
          prerelease: false
      - name: Upload Release File
        uses: actions/upload-artifact@v2
        with:
          name: pentestnotes.pdf
          path: ./output/pentestnotes.pdf